### ISSUE TITLE
Images colour loss solution

### ISSUE THREAD

**Issue by Lord-V15** [j9108c/dark-mode-pdf#1]
First of all, thank you so much. I love using this tool. I'm a night owl and I can't deal with reading bright papers when I get down to work at midnight.
The only problem I face is that sometimes the images are converted into grayscale when inverted.
Is there any way possible to add an option to let the images stay as they are while the text is inverted ?

**Comment by j9108c** [comment]
thanks for the suggestion! ive just implemented this and pushed the change. note this will only work for digital docs

**Comment by j9108c** [comment]
thanks for the suggestion! ive just implemented this and pushed the change to production. note this will only work for digital docs

**Comment by j9108c** [comment]
thanks for the suggestion! ive just implemented this and pushed the change to production. note this will only work for digitally created docs

**Comment by Lord-V15** [comment]
Wow, thanks for replying so quickly and pushing changes to production. the changes you've made are great for images that are in research papers but there are some things you should know. 
</br>This is the image in the original document : 
<img width="507" alt="Screenshot 2021-06-05 at 11 48 49 PM" src="https://user-images.githubusercontent.com/46837998/120901496-eec14f80-c658-11eb-9ff7-8881aff17f3e.png">
</br>This is the image in the old dark mode converter : 
<img width="507" alt="Screenshot 2021-06-05 at 11 52 30 PM" src="https://user-images.githubusercontent.com/46837998/120901517-1d3f2a80-c659-11eb-9805-eb4be72a97b8.png">
</br>And this is the image in the new dark mode converter : 
<img width="507" alt="Screenshot 2021-06-05 at 11 48 25 PM" src="https://user-images.githubusercontent.com/46837998/120901536-3e078000-c659-11eb-88a8-eba2579dea79.png">

**Comment by Lord-V15** [comment]
- As you can see, if the images are actually diagrams, then **I think the converted document renders the text inside these diagrams as white**, hence making it invisible. Is there any way to solve this ?

- Also, I feel it would be really convenient for users if there was **an option to choose whether or not images should be converted into dark mode**. I know it's a big thing to ask, but is it possible to do that? 

- Can I help in any way?

**Comment by j9108c** [comment]
> think the converted document renders the text inside these diagrams as white, hence making it invisible

that's not what the algorithm is doing actually. this is a surprisingly difficult problem. i havent found a way to fully optimize this display problem nor are there any pdf tools out there that can do this afaik. for now, i have added the option to choose whether you want to convert the images or retain the original colors as an experimental feature

**Comment by j9108c** [comment]
> think the converted document renders the text inside these diagrams as white, hence making it invisible

that's not what the algorithm is doing actually. this is a surprisingly difficult problem. i havent found a way to fully optimize this display problem nor are there any pdf tools out there that can do this (programatically) afaik. for now, i have added the option to choose whether you want to convert the images or retain the original colors as an experimental feature

**Comment by j9108c** [comment]
> think the converted document renders the text inside these diagrams as white, hence making it invisible

that's not what the algorithm is doing actually. this is a surprisingly difficult problem. i havent found a way to fully optimize this display problem nor are there any pdf tools out there that can do this (programmatically) afaik. for now, i have added the option to choose whether you want to convert the images or retain the original colors as an experimental feature

**Comment by j9108c** [comment]
> think the converted document renders the text inside these diagrams as white, hence making it invisible

that's not what the algorithm is doing actually. this is a surprisingly difficult problem. i havent found a way to fully optimize this display problem nor are there any pdf tools out there that can do this (programmatically) afaik. for now, i have added the option to choose whether you want to convert the images or retain the original colors as an experimental feature

> Can I help in any way?

feel free to open a pull request if you figure out how to solve this i guess. either way, i appreciate your suggestions and bug reports

**Comment by Lord-V15** [comment]
> + retain image colors (EXPERIMENTAL)

This option is brilliant! **I think this is the ideal solution for now**.
I'm thinking of adding an in-depth readme for users who want to know more about what you've built.

I'm very much interested in the deployment of the website and how you integrated analytics and made those buttons look aesthetically clean. If you can give me some tips, [this](https://www.linkedin.com/in/vibhansh-gupta/) is my LinkedIn.
Oh and expect a cup of coffee from my side as a token of appreciation 😄 ☕
