### ISSUE TITLE
File Doesn't Get Sent to Downloads

### ISSUE THREAD

**Issue by bignuto** [j9108c/dark-mode-pdf#2]
Even after enable automatic downloads + popups/redirects, the site doesn't work

**Comment by j9108c** [comment]
it should be working. ive just tested it and most users don't run into issues either. is it not working for all your pdfs or a specific one?

**Comment by j9108c** [comment]
it should be working. ive just tested it and most users don't run into issues either. is it not working for all your pdfs or a specific one? and are there any error messages in the console?

**Comment by j9108c** [comment]
it should be working. ive just tested it and most users don't run into issues either. is it not working for all your pdfs or a specific one? and are there any error messages in the terminal?

**Comment by bignuto** [comment]
![image](https://user-images.githubusercontent.com/85851209/125505747-3e94a9bd-b516-438b-9fd2-c659ed84e3b5.png)
Tried it with a different PDF

**Comment by j9108c** [comment]
the exit code 1 is probably the server running out of memory while processing your file, even though i have supposedly allocated more than enough memory for a ~200 page pdf.

i have increased the virtual memory by 1/3 now, please try again. if it still doesnt work, do you mind sending me the pdf so i can see what specifically is going wrong? at j9108c@outlook.com. appreciate it.

**Comment by j9108c** [comment]
closed bc inactivity. feel free to reopen if any further issue.
